name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: /Flutter-Responsive-Admin-Panel-or-Dashboard-master/
              baseHref:  # Only works with v2
      # - uses: subosito/flutter-action@v1
      # - uses: bluefireteam/flutter-gh-pages@v7
      
              